//! Predeclared independent IK comparison and restart ablation.
//!
//! ```text
//! cargo run --release -p arm-lab --example ik_baseline -- --write
//! cargo run --release -p arm-lab --example ik_baseline -- --check
//! ```

use std::collections::BTreeMap;
use std::f64::consts::FRAC_PI_2;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use arm_lab::Chain;
use arm_lab::ik::{IkConfig, orientation_error, solve_ik};
use arm_lab::kinematics::fk;
use arm_lab::rng::Rng;
use k::InverseKinematicsSolver as _;
use mujoco_rs::prelude::*;
use nalgebra::Isometry3;

const TARGET_COUNT: usize = 1_000;
const TARGET_SEED: u64 = 0x1C2026;
const RESTART_SEED: u64 = 0x1CF7EE;
const RESTARTS: usize = 8;
const POS_TOL: f64 = 1e-4;
const ROT_TOL: f64 = 1e-3;
const HOME: [f64; 6] = [
    -FRAC_PI_2, -FRAC_PI_2, FRAC_PI_2, -FRAC_PI_2, -FRAC_PI_2, 0.0,
];
const VARIANTS: [&str; 4] = ["arm_cold", "arm_restarts", "k_cold", "k_restarts"];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Mode {
    Print,
    Write,
    Check,
}

#[derive(Debug, Clone)]
struct Target {
    index: usize,
    q: Vec<f64>,
    pose: Isometry3<f64>,
}

#[derive(Debug, Clone)]
struct Outcome {
    target_index: usize,
    variant: &'static str,
    solver_status: &'static str,
    success: bool,
    pos_err: Option<f64>,
    rot_err: Option<f64>,
    q: Option<Vec<f64>>,
}

#[derive(Debug, Clone, Copy, Default)]
struct PairCells {
    both: usize,
    a_only: usize,
    b_only: usize,
    neither: usize,
}

#[derive(Debug)]
struct Artifacts {
    targets_csv: String,
    results_csv: String,
    report: String,
}

fn main() {
    let mode = parse_mode(std::env::args().skip(1));
    let artifacts = generate();
    let docs = project_root().join("docs");

    match mode {
        Mode::Print => print!("{}", artifacts.report),
        Mode::Write => {
            std::fs::write(docs.join("ik_baseline_targets.csv"), &artifacts.targets_csv)
                .expect("write IK target CSV");
            std::fs::write(docs.join("ik_baseline_results.csv"), &artifacts.results_csv)
                .expect("write IK result CSV");
            std::fs::write(docs.join("ik_baseline_results.md"), &artifacts.report)
                .expect("write IK report");
            println!("wrote IK target, result, and report artifacts");
        }
        Mode::Check => {
            check_artifact(
                "IK target CSV",
                &artifacts.targets_csv,
                &std::fs::read_to_string(docs.join("ik_baseline_targets.csv"))
                    .expect("read committed IK target CSV"),
            )
            .unwrap_or_else(|msg| panic!("{msg}"));
            check_artifact(
                "IK result CSV",
                &artifacts.results_csv,
                &std::fs::read_to_string(docs.join("ik_baseline_results.csv"))
                    .expect("read committed IK result CSV"),
            )
            .unwrap_or_else(|msg| panic!("{msg}"));
            check_artifact(
                "IK report",
                &artifacts.report,
                &std::fs::read_to_string(docs.join("ik_baseline_results.md"))
                    .expect("read committed IK report"),
            )
            .unwrap_or_else(|msg| panic!("{msg}"));
            println!("IK artifact check passed; every generated byte matches");
        }
    }
}

fn parse_mode(args: impl Iterator<Item = String>) -> Mode {
    let args: Vec<String> = args.collect();
    match args.as_slice() {
        [] => Mode::Print,
        [arg] if arg == "--write" => Mode::Write,
        [arg] if arg == "--check" => Mode::Check,
        _ => panic!("usage: ik_baseline [--write|--check]"),
    }
}

fn project_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn chain() -> Chain {
    let model_path = project_root().join("assets/ur5e/ur5e.xml");
    let model = MjModel::from_xml(&model_path).expect("load vendored UR5e MJCF");
    Chain::from_mujoco(&model, "ur5e", "wrist_3_link", "attachment_site")
        .expect("extract UR5e chain")
}

fn independent_chain(chain: &Chain) -> k::SerialChain<f64> {
    let urdf_robot =
        urdf_rs::read_from_string(&chain.to_urdf_string()).expect("parse generated URDF");
    let k_chain = k::Chain::from(&urdf_robot);
    let end = k_chain.find_link("ee_tool").expect("generated tool link");
    let serial = k::SerialChain::from_end(end);
    assert_eq!(serial.dof(), chain.dof(), "independent chain DOF mismatch");
    serial
}

fn generate() -> Artifacts {
    let chain = chain();
    assert_eq!(
        chain.dof(),
        HOME.len(),
        "protocol assumes the UR5e six-DOF chain"
    );
    let targets = generate_targets(&chain);
    let restart_starts = generate_restart_starts(&chain);
    let independent = independent_chain(&chain);
    let independent_solver = k::JacobianIkSolver::new(POS_TOL, ROT_TOL, 0.5, 200);

    let mut outcomes = Vec::with_capacity(TARGET_COUNT * VARIANTS.len());
    for target in &targets {
        outcomes.push(run_arm(&chain, target, false));
        outcomes.push(run_arm(&chain, target, true));
        outcomes.push(run_k(
            &chain,
            &independent,
            &independent_solver,
            target,
            &restart_starts[..1],
            "k_cold",
        ));
        outcomes.push(run_k(
            &chain,
            &independent,
            &independent_solver,
            target,
            &restart_starts,
            "k_restarts",
        ));
    }

    validate_outcomes(&chain, &targets, &outcomes);
    Artifacts {
        targets_csv: render_targets_csv(&targets),
        results_csv: render_results_csv(&outcomes),
        report: render_report(&outcomes),
    }
}

fn generate_targets(chain: &Chain) -> Vec<Target> {
    let mut rng = Rng::new(TARGET_SEED);
    (0..TARGET_COUNT)
        .map(|index| {
            let q = chain.sample_uniform(&mut rng);
            let pose = fk(chain, &q);
            Target { index, q, pose }
        })
        .collect()
}

fn generate_restart_starts(chain: &Chain) -> Vec<Vec<f64>> {
    let mut starts = vec![HOME.to_vec()];
    let mut rng = Rng::new(RESTART_SEED);
    for _ in 0..RESTARTS {
        starts.push(chain.sample_uniform(&mut rng));
    }
    starts
}

fn run_arm(chain: &Chain, target: &Target, with_restarts: bool) -> Outcome {
    let cfg = IkConfig {
        restarts: if with_restarts { RESTARTS } else { 0 },
        seed: 0,
        ..IkConfig::default()
    };
    let result = solve_ik(chain, &target.pose, &HOME, Some(&HOME), &cfg);
    let (success, pos_err, rot_err) = common_outcome(chain, &target.pose, &result.q);
    Outcome {
        target_index: target.index,
        variant: if with_restarts {
            "arm_restarts"
        } else {
            "arm_cold"
        },
        solver_status: if result.converged {
            "ok"
        } else {
            "not_converged"
        },
        success,
        pos_err: Some(pos_err),
        rot_err: Some(rot_err),
        q: Some(result.q),
    }
}

fn run_k(
    chain: &Chain,
    independent: &k::SerialChain<f64>,
    solver: &k::JacobianIkSolver<f64>,
    target: &Target,
    starts: &[Vec<f64>],
    variant: &'static str,
) -> Outcome {
    let target_k = to_k_pose(&target.pose);
    let mut last_common_fail = None;
    let mut any_solver_ok = false;

    for start in starts {
        independent
            .set_joint_positions(start)
            .expect("independent solver rejected an in-limit start");
        independent.update_transforms();
        if solver.solve(independent, &target_k).is_err() {
            continue;
        }
        any_solver_ok = true;
        let q = independent.joint_positions();
        let (success, pos_err, rot_err) = common_outcome(chain, &target.pose, &q);
        if success {
            return Outcome {
                target_index: target.index,
                variant,
                solver_status: "ok",
                success: true,
                pos_err: Some(pos_err),
                rot_err: Some(rot_err),
                q: Some(q),
            };
        }
        last_common_fail = Some((q, pos_err, rot_err));
    }

    match last_common_fail {
        Some((q, pos_err, rot_err)) => Outcome {
            target_index: target.index,
            variant,
            solver_status: "common_check_failed",
            success: false,
            pos_err: Some(pos_err),
            rot_err: Some(rot_err),
            q: Some(q),
        },
        None => Outcome {
            target_index: target.index,
            variant,
            solver_status: if any_solver_ok {
                "common_check_failed"
            } else {
                "not_converged"
            },
            success: false,
            pos_err: None,
            rot_err: None,
            q: None,
        },
    }
}

fn to_k_pose(pose: &Isometry3<f64>) -> k::Isometry3<f64> {
    let p = pose.translation.vector;
    let q = pose.rotation;
    k::Isometry3::from_parts(
        k::Translation3::new(p.x, p.y, p.z),
        k::UnitQuaternion::new_normalize(k::nalgebra::Quaternion::new(q.w, q.i, q.j, q.k)),
    )
}

fn common_outcome(chain: &Chain, target: &Isometry3<f64>, q: &[f64]) -> (bool, f64, f64) {
    let finite_and_limited = q.len() == chain.dof()
        && q.iter().zip(chain.joint_limits()).all(|(value, limit)| {
            value.is_finite()
                && limit.is_none_or(|(lo, hi)| *value >= lo - 1e-12 && *value <= hi + 1e-12)
        });
    if !finite_and_limited {
        return (false, f64::INFINITY, f64::INFINITY);
    }
    let actual = fk(chain, q);
    let pos_err = (target.translation.vector - actual.translation.vector).norm();
    let rot_err = orientation_error(&target.rotation, &actual.rotation).norm();
    (
        pos_err.is_finite() && rot_err.is_finite() && pos_err < POS_TOL && rot_err < ROT_TOL,
        pos_err,
        rot_err,
    )
}

fn validate_outcomes(chain: &Chain, targets: &[Target], outcomes: &[Outcome]) {
    assert_eq!(targets.len(), TARGET_COUNT);
    assert_eq!(outcomes.len(), TARGET_COUNT * VARIANTS.len());
    for (expected_index, target) in targets.iter().enumerate() {
        assert_eq!(target.index, expected_index);
        assert!(joint_vector_within_limits(chain, &target.q));
    }
    for target in targets {
        let rows: Vec<&Outcome> = outcomes
            .iter()
            .filter(|row| row.target_index == target.index)
            .collect();
        assert_eq!(rows.len(), VARIANTS.len());
        for (row, expected_variant) in rows.iter().zip(VARIANTS) {
            assert_eq!(row.variant, expected_variant);
            if let Some(q) = &row.q {
                let (success, pos_err, rot_err) = common_outcome(chain, &target.pose, q);
                assert_eq!(row.success, success);
                assert_eq!(row.pos_err, Some(pos_err));
                assert_eq!(row.rot_err, Some(rot_err));
                if row.success {
                    assert!(joint_vector_within_limits(chain, q));
                }
            } else {
                assert!(!row.success);
                assert!(row.pos_err.is_none() && row.rot_err.is_none());
            }
        }
    }
}

fn joint_vector_within_limits(chain: &Chain, q: &[f64]) -> bool {
    q.len() == chain.dof()
        && q.iter().zip(chain.joint_limits()).all(|(value, limit)| {
            value.is_finite()
                && limit.is_none_or(|(lo, hi)| *value >= lo - 1e-12 && *value <= hi + 1e-12)
        })
}

fn render_targets_csv(targets: &[Target]) -> String {
    let mut csv = String::from(
        "target_index,q1_rad,q2_rad,q3_rad,q4_rad,q5_rad,q6_rad,px_m,py_m,pz_m,qw,qx,qy,qz\n",
    );
    for target in targets {
        let p = target.pose.translation.vector;
        let q = target.pose.rotation;
        writeln!(
            csv,
            "{},{:.15},{:.15},{:.15},{:.15},{:.15},{:.15},{:.15},{:.15},{:.15},{:.15},{:.15},{:.15},{:.15}",
            target.index,
            target.q[0],
            target.q[1],
            target.q[2],
            target.q[3],
            target.q[4],
            target.q[5],
            p.x,
            p.y,
            p.z,
            q.w,
            q.i,
            q.j,
            q.k
        )
        .expect("format IK target row");
    }
    csv
}

fn render_results_csv(outcomes: &[Outcome]) -> String {
    let mut csv = String::from(
        "target_index,variant,solver_status,success,pos_err_m,rot_err_rad,q1_rad,q2_rad,q3_rad,q4_rad,q5_rad,q6_rad\n",
    );
    for row in outcomes {
        write!(
            csv,
            "{},{},{},{},",
            row.target_index, row.variant, row.solver_status, row.success
        )
        .expect("format IK result prefix");
        match (row.pos_err, row.rot_err, row.q.as_deref()) {
            (Some(pos_err), Some(rot_err), Some(q)) => {
                writeln!(
                    csv,
                    "{pos_err:.15},{rot_err:.15},{:.15},{:.15},{:.15},{:.15},{:.15},{:.15}",
                    q[0], q[1], q[2], q[3], q[4], q[5]
                )
                .expect("format IK result row");
            }
            (None, None, None) => csv.push_str(",,,,,,,\n"),
            _ => panic!("partial IK result fields"),
        }
    }
    csv
}

fn render_report(outcomes: &[Outcome]) -> String {
    let by_variant = outcomes_by_variant(outcomes);
    let arm_cold = &by_variant["arm_cold"];
    let arm_restarts = &by_variant["arm_restarts"];
    let k_cold = &by_variant["k_cold"];
    let k_restarts = &by_variant["k_restarts"];

    let arm_pair = paired_cells(arm_cold, arm_restarts);
    let k_pair = paired_cells(k_cold, k_restarts);
    let cross_pair = paired_cells(arm_restarts, k_restarts);
    let p_value = exact_two_sided_sign(cross_pair.a_only, cross_pair.b_only);
    let union = arm_restarts
        .iter()
        .zip(k_restarts)
        .filter(|(a, b)| a.success || b.success)
        .count();

    let mut report = String::from(
        "# Independent IK baseline results\n\n\
         This result follows the [predeclared protocol](ik_baseline_protocol.md). The existing 97.8% arm-lab restart-enabled control was known before protocol freeze; the cold-start and independent `k` outcomes were not. All 1,000 targets and all four variant outcomes are retained. **This is full-pose, reachable-by-construction, collision-unaware kinematic evidence in simulation—not a Cartesian-uniform task distribution, runtime ranking, hardware result, or sim-to-real claim.**\n\n\
         ## Common success results\n\n\
         Every success is re-evaluated with arm-lab FK at `< 1e-4 m` position error, `< 1e-3 rad` orientation error, finite values, and compiled joint limits.\n\n\
         | Variant | Success | Rate (Wilson 95% CI) | Median position error (m) | Worst position error (m) | Median rotation error (rad) | Worst rotation error (rad) |\n\
         |---|---:|---:|---:|---:|---:|---:|\n",
    );
    for variant in VARIANTS {
        let rows = &by_variant[variant];
        let success = rows.iter().filter(|row| row.success).count();
        let (lo, hi) = wilson(success, TARGET_COUNT);
        let error_cells = successful_error_summary(rows)
            .map(|(pos_median, pos_worst, rot_median, rot_worst)| {
                [
                    format!("{pos_median:.3e}"),
                    format!("{pos_worst:.3e}"),
                    format!("{rot_median:.3e}"),
                    format!("{rot_worst:.3e}"),
                ]
            })
            .unwrap_or_else(|| std::array::from_fn(|_| "n/a".to_string()));
        writeln!(
            report,
            "| `{variant}` | {success}/{TARGET_COUNT} | {:.1}% ({:.1}–{:.1}%) | {} | {} | {} | {} |",
            percent(success, TARGET_COUNT),
            100.0 * lo,
            100.0 * hi,
            error_cells[0],
            error_cells[1],
            error_cells[2],
            error_cells[3]
        )
        .expect("format IK result table");
    }

    write!(
        report,
        "\n## Restart ablations\n\n\
         | Pair | Both | Cold only | Restarts only | Neither |\n\
         |---|---:|---:|---:|---:|\n\
         | arm-lab cold vs restarts | {} | {} | {} | {} |\n\
         | `k` cold vs restarts | {} | {} | {} | {} |\n\n\
         ## Restart-enabled cross-implementation comparison\n\n\
         | Both | arm-lab only | `k` only | Neither | Union solved |\n\
         |---:|---:|---:|---:|---:|\n\
         | {} | {} | {} | {} | {}/{TARGET_COUNT} |\n\n\
         The exact two-sided sign/McNemar test over the {} discordant restart-enabled targets is `p = {:.3e}`. It is descriptive for this one deterministic cohort, not a universal solver ranking. The maximum attempt and iteration caps are matched, but per-iteration work and early stopping are not; runtime and compute are not compared.\n\n\
         ## Scope and retention\n\n\
         - Targets are generated by FK from in-limit configurations and are therefore reachable under arm-lab's exact model. They are not collision-filtered or Cartesian-uniform.\n\
         - The independent solver consumes the generated URDF. Existing tests cross-check that chain's FK against arm-lab below `1e-9`; every reported success is nevertheless rechecked through arm-lab FK.\n\
         - Alternative joint solutions are accepted when they meet the common pose and limit rule. Failure residuals are not compared because `k` restores a failed attempt's start while arm-lab returns its best attempt.\n\
         - No variant, failure, or discordant target was removed after outcomes were observed.\n\n\
         ## Reproduce\n\n\
         ```bash\n\
         cargo run --release -p arm-lab --example ik_baseline -- --write\n\
         cargo run --release -p arm-lab --example ik_baseline -- --check\n\
         ```\n",
        arm_pair.both,
        arm_pair.a_only,
        arm_pair.b_only,
        arm_pair.neither,
        k_pair.both,
        k_pair.a_only,
        k_pair.b_only,
        k_pair.neither,
        cross_pair.both,
        cross_pair.a_only,
        cross_pair.b_only,
        cross_pair.neither,
        union,
        cross_pair.a_only + cross_pair.b_only,
        p_value
    )
    .expect("format IK report");
    report
}

fn outcomes_by_variant(outcomes: &[Outcome]) -> BTreeMap<&'static str, Vec<&Outcome>> {
    let mut map = BTreeMap::new();
    for variant in VARIANTS {
        map.insert(
            variant,
            outcomes
                .iter()
                .filter(|row| row.variant == variant)
                .collect(),
        );
    }
    map
}

fn paired_cells(a: &[&Outcome], b: &[&Outcome]) -> PairCells {
    assert_eq!(a.len(), b.len());
    let mut cells = PairCells::default();
    for (a, b) in a.iter().zip(b) {
        assert_eq!(a.target_index, b.target_index);
        match (a.success, b.success) {
            (true, true) => cells.both += 1,
            (true, false) => cells.a_only += 1,
            (false, true) => cells.b_only += 1,
            (false, false) => cells.neither += 1,
        }
    }
    cells
}

fn successful_error_summary(rows: &[&Outcome]) -> Option<(f64, f64, f64, f64)> {
    let mut pos: Vec<f64> = rows
        .iter()
        .filter(|row| row.success)
        .map(|row| row.pos_err.expect("successful row has position error"))
        .collect();
    let mut rot: Vec<f64> = rows
        .iter()
        .filter(|row| row.success)
        .map(|row| row.rot_err.expect("successful row has rotation error"))
        .collect();
    assert_eq!(pos.len(), rot.len());
    if pos.is_empty() {
        return None;
    }
    pos.sort_by(f64::total_cmp);
    rot.sort_by(f64::total_cmp);
    Some((
        median(&pos),
        *pos.last().expect("nonempty position errors"),
        median(&rot),
        *rot.last().expect("nonempty rotation errors"),
    ))
}

fn median(sorted: &[f64]) -> f64 {
    let mid = sorted.len() / 2;
    if sorted.len().is_multiple_of(2) {
        (sorted[mid - 1] + sorted[mid]) / 2.0
    } else {
        sorted[mid]
    }
}

fn wilson(success: usize, total: usize) -> (f64, f64) {
    assert!(success <= total && total > 0);
    let n = total as f64;
    let p = success as f64 / n;
    let z = 1.959_963_984_540_054;
    let z2 = z * z;
    let denominator = 1.0 + z2 / n;
    let center = (p + z2 / (2.0 * n)) / denominator;
    let half = z * ((p * (1.0 - p) / n + z2 / (4.0 * n * n)).sqrt()) / denominator;
    (center - half, center + half)
}

fn exact_two_sided_sign(a_only: usize, b_only: usize) -> f64 {
    let discordant = a_only + b_only;
    if discordant == 0 {
        return 1.0;
    }
    let small = a_only.min(b_only);
    if 2 * small >= discordant {
        return 1.0;
    }
    let mut probability = 2f64.powi(-(discordant as i32));
    let mut cumulative = probability;
    for i in 1..=small {
        probability *= (discordant - i + 1) as f64 / i as f64;
        cumulative += probability;
    }
    (2.0 * cumulative).min(1.0)
}

fn percent(success: usize, total: usize) -> f64 {
    success as f64 / total as f64 * 100.0
}

fn check_artifact(label: &str, generated: &str, committed: &str) -> Result<(), String> {
    if generated == committed {
        Ok(())
    } else {
        Err(format!("{label} is stale; rerun ik_baseline --write"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn row(index: usize, success: bool) -> Outcome {
        Outcome {
            target_index: index,
            variant: "test",
            solver_status: "test",
            success,
            pos_err: None,
            rot_err: None,
            q: None,
        }
    }

    #[test]
    fn paired_cells_count_every_row() {
        let a = [row(0, true), row(1, true), row(2, false), row(3, false)];
        let b = [row(0, true), row(1, false), row(2, true), row(3, false)];
        let a_refs: Vec<&Outcome> = a.iter().collect();
        let b_refs: Vec<&Outcome> = b.iter().collect();
        let cells = paired_cells(&a_refs, &b_refs);
        assert_eq!(
            (cells.both, cells.a_only, cells.b_only, cells.neither),
            (1, 1, 1, 1)
        );
    }

    #[test]
    fn exact_sign_test_is_symmetric_and_bounded() {
        assert_eq!(exact_two_sided_sign(0, 0), 1.0);
        assert_eq!(exact_two_sided_sign(4, 4), 1.0);
        let p = exact_two_sided_sign(1, 9);
        assert!((p - exact_two_sided_sign(9, 1)).abs() < f64::EPSILON);
        assert!(p > 0.0 && p < 1.0);
    }

    #[test]
    fn wilson_interval_contains_observed_rate() {
        let (lo, hi) = wilson(978, 1_000);
        assert!(lo < 0.978 && 0.978 < hi);
    }

    #[test]
    fn artifact_check_rejects_one_byte_change() {
        assert!(check_artifact("test", "abc\n", "abc\n").is_ok());
        let error = check_artifact("test", "abc\n", "abd\n").expect_err("mutation must fail");
        assert!(error.contains("stale"));
    }

    #[test]
    fn zero_success_summary_is_supported() {
        let rows = [row(0, false), row(1, false)];
        let refs: Vec<&Outcome> = rows.iter().collect();
        assert!(successful_error_summary(&refs).is_none());
    }
}
